server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password: Nut_221044
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: nnutthanapon@gmail.com
    password: ljawpfvjvlpzbsen
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

#  mail:
#    host: localhost
#    port: 1025
#    username: nnutthanapon@gmail.com
#    password: ljawpfvjvlpzbsen
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000
